name: pyuvsim
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy>=4.0
  - astropy-healpix
  - line_profiler
  - mpi4py>=3.0.0
  - numpy>=1.15
  - pip
  - pre-commit
  - psutil
  - pypandoc
  - python-casacore>=3.1.0
  - pytest
  - pytest-cov
  - pyuvdata>=2.1.5
  - pyyaml>=5.1
  - scipy>=1.0.1
  - setuptools>=38.4.0
  - setuptools_scm
  - sphinx
  - pip:
    - pyradiosky>=0.1.2
    - lunarsky
    - git+git://github.com/aelanman/analytic_diffuse
