name: pyuvsim
channels:
  - conda-forge
dependencies:
  - astropy>=6.0
  - astropy-healpix>=1.0.2
  - line_profiler
  - mpi4py>=3.1.1
  - numpy>=1.23
  - pip
  - pre-commit
  - psutil
  - pypandoc
  - python-casacore>=3.5.2
  - pytest
  - pytest-cov>=5.0.0
  - pytest-xdist
  - pyuvdata>=2.4.3
  - pyyaml>=5.4.1
  - scipy>=1.8
  - setuptools_scm>=8.1
  - sphinx
  - pip:
    - pyradiosky>=0.2
    - lunarsky>=0.2.2
    - git+https://github.com/aelanman/analytic_diffuse
