name: pyuvsim
channels:
  - conda-forge
dependencies:
  - astropy>=5.2
  - astropy-healpix>=0.6
  - line_profiler
  - mpi4py>=3.0.0
  - numpy>=1.20
  - pip
  - pre-commit
  - psutil
  - pypandoc
  - python-casacore>=3.3
  - pytest
  - pytest-cov
  - pyuvdata>=2.4.1
  - pyyaml>=5.1
  - scipy>=1.3
  - setuptools>=38.4.0
  - setuptools_scm>=7.0.3
  - sphinx
  - pip:
    - pyradiosky>=0.2
    - lunarsky>=0.2.1
    - git+https://github.com/aelanman/analytic_diffuse
