name: pyuvsim
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy>=4.0
  - h5py
  - line_profiler
  - mpi4py>=3.0.0
  - numpy>=1.15
  - pip
  - psutil
  - pypandoc
  - pytest
  - pytest-cov
  - pyuvdata
  - pyyaml>=5.1
  - scipy>=1.0.1
  - setuptools>=38.4.0
  - sphinx
  - pip:
    - git+https://github.com/RadioAstronomySoftwareGroup/pyradiosky.git
    - pre-commit
