name: pyuvsim
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy>=4.0
  - h5py
  - line_profiler
  - mpi4py>=3.0.0
  - numpy>=1.15
  - pip
  - psutil
  - pypandoc
  - pyradiosky
  - pytest
  - pytest-cov
  - pytest-mpi
  - pyuvdata
  - pyyaml>=5.1
  - scipy>=1.0.1
  - setuptools>=38.4.0
  - setuptools_scm
  - sphinx
  - pip:
    - pre-commit
    - pyradiosky
    - lunarsky
    - git+git://github.com/aelanman/analytic_diffuse
