Nants: 3
beam_paths:
  0: /users/alanman/data/alanman/NickFagnoniBeams/HERA_NicCST_fullfreq.uvbeam
telescope_location: (-30.72152777777791, 21.428305555555557, 1073.0000000093132)
telescope_name: TRIANGLE
